FROM registry.access.redhat.com/ubi8
RUN yum install -y  httpd openssh-clients net-tools iproute iputils bind-utils wget curl && yum clean all
RUN echo -e "It works\n" > /var/www/html/index.html
EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]
